from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
DEFAULT_SPEC = HERE / "compositional-invariant-spec-v1.0.json"
DEFAULT_RESULT = HERE / "compositional-invariant-result-v1.0.json"
DEFAULT_REPORT = HERE / "compositional-invariant-terminal-result-v1.0.md"

EXPECTED_BASE = "d1fc8053e1459a7829f6f24b8d187f7887375cf0"
EXPECTED_SPEC_SHA256 = "733b8162fa2228d2be2018bd9eab79e8c096beeb21f09ac1cde50a7b9faccbf6"
EXPECTED_REPORT_SHA256 = "734be42e44dcad48a057fb14126ebe59f5c270b40b6a68d331c4b3181a4f4ce4"
EXPECTED_QUESTION = (
    "What is the broadest independently stated structured class in which "
    "nontrivial operations are invariant under admissible recoding, without "
    "assuming RCCD components?"
)
EXPECTED_SCHEMA = {
    "input": "a finite directed graph G with distinguished vertices s and t",
    "presentation": "a graph map from G into the underlying graph of a small category C",
    "output": "an arrow from the image of s to the image of t",
    "invariance": "for every functor H:C->D, H(alpha_C(x)) = alpha_D(H composed with x)",
}
EXPECTED_CLAIMS = [
    {
        "id": "TCD-CI-T1",
        "statement": "TC1-TC4 characterize small categories and functors as the corresponding recodings.",
        "status": "proved_in_report",
    },
    {
        "id": "TCD-CI-T2",
        "statement": "Every finitary arrow-valued operation invariant under all functors is evaluation of one fixed path in the free category on its input graph; conversely every such path defines an invariant operation.",
        "status": "proved_in_report",
    },
    {
        "id": "TCD-CI-C1",
        "statement": "Identity and sequential composition are common nontrivial invariants whenever the input graph contains a genuinely composable chain.",
        "status": "corollary",
    },
    {
        "id": "TCD-CI-C2",
        "statement": "No RCCD-specific generator, operator, observation, objective, or decomposition follows from typed composition alone.",
        "status": "corollary",
    },
]
EXPECTED_POLICY = {
    "absolute_maximum_claimed": False,
    "reason": "Broadest is undefined until a comparison order and admissible recodings are fixed.",
    "selected_scope": "all small typed compositional systems",
    "scope_criterion": "A system is included exactly when its typed steps have identities and associative sequential composition.",
    "recodings": "all functors",
}
EXPECTED_AXIOMS = [
    {"id": "TC1", "statement": "Every step has a source interface and a target interface."},
    {"id": "TC2", "statement": "Every interface has an identity step."},
    {"id": "TC3", "statement": "Whenever the target of one step equals the source of another, their sequential composite exists."},
    {"id": "TC4", "statement": "Identity steps are two-sided units and sequential composition is associative."},
]
EXPECTED_FIXTURE = {
    "objects": ["A", "B", "C"],
    "generators": [
        {"name": "a", "source": "A", "target": "B"},
        {"name": "b", "source": "B", "target": "C"},
        {"name": "c", "source": "A", "target": "C"},
    ],
    "distinguished_source": "A",
    "distinguished_target": "C",
    "expected_paths_from_source_to_target": ["c", "b∘a"],
    "expected_new_nonidentity_paths_after_free_completion": ["b∘a"],
}
EXPECTED_DISPOSITION = {
    "classification": "scoped_theoretical_question_closed",
    "strongest_claim": "Across all small typed compositional systems and all functorial recodings, the complete finitary arrow-valued invariant operations are path terms generated by identities and sequential composition.",
    "empirical_program_status": "not_executed",
    "rccd_status": "not_derived",
    "remaining_question": "Whether RCCD or another richer basis is necessary, economical, or Pareto-optimal for the separately chosen explicitly auditable-artifact class remains empirical and open.",
}
EXPECTED_NONCLAIMS = {
    "small categories are the absolute broadest possible class of every conceivable reasoning system",
    "all reasoning is sequential",
    "typed composition is a complete architecture of reasoning",
    "RCCD is false",
    "RCCD is necessary, minimal, unique, or Pareto-optimal",
    "the clean-room target-category study has been executed",
    "the result changes accepted Project FAR theory",
}


class VerificationError(ValueError):
    pass


def _reject_constant(value: str) -> None:
    raise VerificationError(f"non-finite JSON number rejected: {value}")


def _no_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key, value in pairs:
        if key in out:
            raise VerificationError(f"duplicate JSON key rejected: {key}")
        out[key] = value
    return out


def load_json(path: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        raise VerificationError(f"UTF-8 BOM rejected: {path}")
    try:
        value = json.loads(
            raw.decode("utf-8"),
            object_pairs_hook=_no_duplicate_keys,
            parse_constant=_reject_constant,
        )
    except UnicodeDecodeError as exc:
        raise VerificationError(f"invalid UTF-8 in {path}") from exc
    except json.JSONDecodeError as exc:
        raise VerificationError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise VerificationError(f"top-level JSON object required: {path}")
    return value


def canonical_json(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def _validate_spec(spec: dict[str, Any]) -> None:
    expected_keys = {
        "id", "version", "status", "base_commit", "question",
        "broadness_policy", "axioms", "input_operation_schema",
        "theorem_claims", "fixture", "terminal_disposition", "nonclaims",
    }
    if set(spec) != expected_keys:
        raise VerificationError("spec top-level keys drifted")
    if (spec["id"], spec["version"], spec["status"]) != (
        "TCD-COMPOSITIONAL-INVARIANT-001", "1.0", "Research"
    ):
        raise VerificationError("spec identity/version/status drifted")
    base = spec["base_commit"]
    if not isinstance(base, str) or re.fullmatch(r"[0-9a-f]{40}", base) is None:
        raise VerificationError("base_commit must be a lowercase 40-character hexadecimal SHA")
    if base != EXPECTED_BASE:
        raise VerificationError("base_commit does not match the frozen repository base")
    if spec["question"] != EXPECTED_QUESTION:
        raise VerificationError("research question drifted")
    if spec["broadness_policy"] != EXPECTED_POLICY:
        raise VerificationError("broadness policy drifted")
    if spec["axioms"] != EXPECTED_AXIOMS:
        raise VerificationError("exact four-axiom contract required")
    if spec["input_operation_schema"] != EXPECTED_SCHEMA:
        raise VerificationError("input operation schema drifted")
    if spec["theorem_claims"] != EXPECTED_CLAIMS:
        raise VerificationError("theorem claim registry or semantics drifted")
    if spec["fixture"] != EXPECTED_FIXTURE:
        raise VerificationError("bounded fixture drifted")
    if spec["terminal_disposition"] != EXPECTED_DISPOSITION:
        raise VerificationError("terminal disposition or claim boundary drifted")
    nonclaims = spec["nonclaims"]
    if not isinstance(nonclaims, list) or set(nonclaims) != EXPECTED_NONCLAIMS:
        raise VerificationError("nonclaim set drifted")
    if hashlib.sha256(canonical_json(spec)).hexdigest() != EXPECTED_SPEC_SHA256:
        raise VerificationError("frozen specification content drifted")


def _free_category() -> tuple[list[tuple[str, tuple[str, ...]]], dict[str, tuple[str, str]]]:
    generators = {g["name"]: (g["source"], g["target"]) for g in EXPECTED_FIXTURE["generators"]}
    outgoing: dict[str, list[str]] = {obj: [] for obj in EXPECTED_FIXTURE["objects"]}
    for name, (source, _) in generators.items():
        outgoing[source].append(name)

    def target(path: tuple[str, tuple[str, ...]]) -> str:
        current = path[0]
        for edge in path[1]:
            source, destination = generators[edge]
            if source != current:
                raise VerificationError("ill-typed path")
            current = destination
        return current

    paths: list[tuple[str, tuple[str, ...]]] = []
    def extend(path: tuple[str, tuple[str, ...]]) -> None:
        paths.append(path)
        for edge in outgoing[target(path)]:
            extend((path[0], path[1] + (edge,)))
    for obj in EXPECTED_FIXTURE["objects"]:
        extend((obj, ()))
    return sorted(set(paths), key=lambda p: (p[0], len(p[1]), p[1])), generators


def _render(path: tuple[str, tuple[str, ...]]) -> str:
    return f"id_{path[0]}" if not path[1] else "∘".join(reversed(path[1]))


def build_result(spec: dict[str, Any]) -> dict[str, Any]:
    _validate_spec(spec)
    arrows, generators = _free_category()

    def target(path: tuple[str, tuple[str, ...]]) -> str:
        current = path[0]
        for edge in path[1]:
            source, destination = generators[edge]
            if source != current:
                raise VerificationError("ill-typed path")
            current = destination
        return current

    def compose(first: tuple[str, tuple[str, ...]], second: tuple[str, tuple[str, ...]]) -> tuple[str, tuple[str, ...]]:
        if target(first) != second[0]:
            raise VerificationError("non-composable arrows")
        return first[0], first[1] + second[1]

    identity_checks = 0
    for arrow in arrows:
        if compose((arrow[0], ()), arrow) != arrow or compose(arrow, (target(arrow), ())) != arrow:
            raise VerificationError("identity law failed")
        identity_checks += 2
    associativity_checks = 0
    for first in arrows:
        for second in arrows:
            if target(first) != second[0]:
                continue
            for third in arrows:
                if target(second) != third[0]:
                    continue
                if compose(compose(first, second), third) != compose(first, compose(second, third)):
                    raise VerificationError("associativity failed")
                associativity_checks += 1

    distinguished = [_render(p) for p in arrows if p[0] == "A" and target(p) == "C"]
    if distinguished != ["c", "b∘a"]:
        raise VerificationError("distinguished path set drifted")
    composite = compose(("A", ("a",)), ("B", ("b",)))
    if _render(composite) != "b∘a":
        raise VerificationError("nontrivial composite witness changed")
    nonidentity = {_render(p) for p in arrows if p[1]}
    new_paths = sorted(nonidentity - set(generators))
    if new_paths != ["b∘a"]:
        raise VerificationError("free-completion witness set drifted")
    words = {"a": "x", "b": "yz", "c": "q"}
    word = "".join(words[e] for e in composite[1])
    if word != "xyz" or len(word) != len(words["a"]) + len(words["b"]):
        raise VerificationError("functorial recoding witness failed")

    evidence = {
        "fixture_object_count": 3,
        "fixture_generator_count": 3,
        "free_category_arrow_count": len(arrows),
        "free_category_nonidentity_arrow_count": len(nonidentity),
        "new_nonidentity_path_count": len(new_paths),
        "new_nonidentity_paths": new_paths,
        "distinguished_path_count": len(distinguished),
        "distinguished_paths": distinguished,
        "nontrivial_composite": "b∘a",
        "graph_only_has_composite": False,
        "free_category_has_composite": True,
        "identity_law_checks": identity_checks,
        "associativity_checks": associativity_checks,
        "word_functor_composite": word,
        "length_recoding_composite": len(word),
        "path_term_classification_witness": "The operation's value on the identity presentation in the free category selects one path; naturality forces every other value to be that path's image.",
    }
    result = {
        "id": "TCD-COMPOSITIONAL-INVARIANT-001",
        "version": "1.0",
        "status": "Research",
        "classification": "scoped_theoretical_question_closed",
        "theorem_status": "hand_proof_with_bounded_executable_corroboration",
        "strongest_claim": EXPECTED_DISPOSITION["strongest_claim"],
        "rccd_status": "not_derived",
        "empirical_program_status": "not_executed",
        "evidence": evidence,
        "nonclaims": sorted(EXPECTED_NONCLAIMS),
    }
    result["evidence_sha256"] = hashlib.sha256(canonical_json(evidence)).hexdigest()
    return result


def _validate_report(path: Path) -> None:
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        raise VerificationError(f"UTF-8 BOM rejected: {path}")
    try:
        raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise VerificationError(f"invalid UTF-8 in {path}") from exc
    if hashlib.sha256(raw).hexdigest() != EXPECTED_REPORT_SHA256:
        raise VerificationError("terminal report content drifted from the frozen proof and claim boundary")


def verify(spec_path: Path = DEFAULT_SPEC, result_path: Path = DEFAULT_RESULT, report_path: Path = DEFAULT_REPORT) -> dict[str, Any]:
    actual = build_result(load_json(spec_path))
    if actual != load_json(result_path):
        raise VerificationError("committed result does not match a fresh rebuild")
    _validate_report(report_path)
    return actual


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    parser.add_argument("--result", type=Path, default=DEFAULT_RESULT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    actual = build_result(load_json(args.spec))
    if args.write:
        args.result.write_text(json.dumps(actual, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    elif actual != load_json(args.result):
        raise VerificationError("committed result does not match a fresh rebuild")
    _validate_report(args.report)
    print(f"PASS: typed-compositional invariant result; {actual['evidence']['free_category_arrow_count']} arrows; paths={actual['evidence']['distinguished_paths']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
