#!/usr/bin/env python3
"""Validate FARA-ARCH-W3-001 and deterministically generate its report."""
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OBJECT = ROOT / "theory/evaluation/fara-w3-common-architecture-v1.0.json"
REPORT = ROOT / "theory/evaluation/generated-fara-w3-common-architecture-report.md"
FAMILIES = [
    "deterministic_state_transition", "probabilistic", "nonmonotonic", "paraconsistent", "causal",
    "continuous_or_hybrid", "embodied_or_sensor_coupled", "changing_rules_or_ontologies",
    "distributed_or_multi_agent", "semantic_interpretation_or_oracle_access",
]
DIMENSIONS = {"structural", "semantic", "operational", "dependency", "information", "historical"}
REQUIRED_FIELDS = {"mapping", "native_structure", "representation_artifacts", "added_machinery", "preservation", "countermodel_search", "loss_failure_ambiguity", "adjudication"}
ALLOWED_PRESERVATION_PREFIXES = ("preserved", "unresolved", "ambiguous", "not_preserved")
EXPECTED_SYSTEM_CLASS = "C_W3 is exactly the ten named family specimens in family_results; it is a challenge set, not all reasoning systems and not a statistically representative population."
EXPECTED_SEPARATED_CLAIMS = {
    "existential_common_structure": "established only for B_W3_closed_explicit below",
    "representational_reconstruction": "mixed across the ten specimens",
    "necessity": "not_established",
    "uniqueness": "refuted_by_multiple_trace_and_event_structure_reconstructions",
    "universality": "refuted_for_internal_state_only_lossless_form; otherwise unresolved outside frozen domains",
}
EXPECTED_OBLIGATIONS = [
    "Freeze a non-candidate-defined population if a claim beyond the ten challenge specimens is sought.",
    "Give an independently justified non-vacuity bound on typed payload and oracle machinery.",
    "Define semantic identity across ontology change.",
    "Choose partial-order rather than total-trace historical equivalence for distributed systems or accept historical loss.",
    "Prove or refute exact preservation for continuous noncomputable and Zeno dynamics.",
    "Test embodied systems without treating the whole environment as hidden state.",
    "Obtain independent counterexample replication before any promotion.",
]


def render(data: dict) -> str:
    rows = []
    for item in data["family_results"]:
        failed = ", ".join(k for k, v in item["preservation"].items() if not v.startswith("preserved")) or "none recorded"
        rows.append(f"| `{item['id']}` | `{item['family']}` | `{item['adjudication']}` | {failed} | {', '.join(item['added_machinery'])} |")
    adj = data["adjudication"]
    return """<!-- Generated by tools/check_fara_common_architecture_w3.py; do not edit. -->
# FARA W3 common-architecture generated report

Status: `{status}`
Object: `{object_id}`

## Exact proposition and frozen boundary

{exact}

- **Class:** {system_class}
- **Equivalence:** {equivalence}
- **Candidate:** `{candidate}`
- **Auxiliary machinery rule:** {machinery}

## Adversarial family results

| ID | Family | Adjudication | Non-preserved, ambiguous, or unresolved dimensions | Charged machinery |
|---|---|---|---|---|
{rows}

## Fail-closed adjudication

**Strongest established:** {strongest}

**Refuted:** {refuted}.

**Unresolved:** {unresolved}.

No successful encoding establishes necessity, uniqueness, minimality, native constitution, or open-world universality.
""".format(
        status=data["status"], object_id=data["id"], exact=data["proposition"]["exact"],
        system_class=data["proposition"]["system_class"], equivalence=data["proposition"]["equivalence"],
        candidate=data["proposition"]["candidate_architecture"], machinery=data["proposition"]["admissible_auxiliary_machinery"],
        rows="\n".join(rows), strongest=adj["strongest_established"], refuted="; ".join(adj["refuted"]),
        unresolved="; ".join(adj["unresolved"]),
    )


def validate(data: dict) -> list[str]:
    errors = []
    if data.get("id") != "FARA-ARCH-W3-001": errors.append("proof object identity changed")
    if data.get("schema_version") != "1.0": errors.append("schema version changed")
    if data.get("status") != "complete_fail_closed_bounded_and_counterexample_adjudication": errors.append("fail-closed status changed")
    upstream = data.get("authority_recovery", {}).get("frozen_upstream", {})
    if set(upstream) != {"W0", "W1", "W2"} or "unresolved" not in upstream.get("W1", "") or "bounded" not in upstream.get("W2", ""):
        errors.append("frozen W0-W2 boundary omitted or promoted")
    prop = data.get("proposition", {})
    separated = prop.get("separated_claims", {})
    system_class = prop.get("system_class", "")
    if system_class != EXPECTED_SYSTEM_CLASS:
        errors.append("system class description changed or scope expanded")
    if any(term in system_class.lower() for term in ("contains all reasoning systems", "includes all reasoning systems", "all systems are members", "unbounded class")):
        errors.append("forbidden scope expansion language")
    strongest = data.get("adjudication", {}).get("strongest_established", "").lower()
    if any(x in strongest for x in ("universal architecture established", "necessity established", "unique architecture established")):
        errors.append("bounded result was promoted")
    if set(prop.get("preservation_dimensions", [])) != DIMENSIONS: errors.append("six-dimensional preservation contract changed")
    if separated != EXPECTED_SEPARATED_CLAIMS:
        errors.append("claim ladder changed, contradicted, or promoted")
    records = data.get("family_results", [])
    if [x.get("family") for x in records] != FAMILIES: errors.append("required family coverage/order changed")
    if len({x.get("id") for x in records}) != 10: errors.append("family IDs missing or duplicated")
    for item in records:
        missing = REQUIRED_FIELDS - set(item)
        if missing: errors.append(f"{item.get('id')} omitted {sorted(missing)}")
        preservation = item.get("preservation", {})
        if set(preservation) != DIMENSIONS:
            errors.append(f"{item.get('id')} omitted a preservation dimension")
        invalid = [value for value in preservation.values() if not isinstance(value, str) or not value.startswith(ALLOWED_PRESERVATION_PREFIXES)]
        if invalid: errors.append(f"{item.get('id')} uses invalid preservation outcomes")
        if item.get("adjudication") == "unresolved" and preservation and all(value.startswith("preserved") for value in preservation.values()):
            errors.append(f"{item.get('id')} unresolved adjudication was silently promoted")
        if not item.get("added_machinery"): errors.append(f"{item.get('id')} hides auxiliary machinery")
        if not item.get("countermodel_search"): errors.append(f"{item.get('id')} lacks adversarial search")
        if not item.get("loss_failure_ambiguity"): errors.append(f"{item.get('id')} omits failure/loss")
    if not any(x.get("adjudication") == "unresolved" for x in records): errors.append("omitted unresolved cases")
    oracle = next((x for x in records if x.get("family") == FAMILIES[-1]), {})
    if not oracle.get("adjudication", "").startswith("counterexample") or not any(v.startswith("not_preserved") for v in oracle.get("preservation", {}).values()):
        errors.append("oracle counterexample or its preservation failures were suppressed")
    adj = data.get("adjudication", {})
    if "B_W3_closed_explicit" not in adj.get("strongest_established", ""): errors.append("strongest claim escaped bounded class")
    if len(adj.get("refuted", [])) < 2 or len(adj.get("unresolved", [])) < 3: errors.append("terminal failures are incomplete")
    if data.get("remaining_obligations") != EXPECTED_OBLIGATIONS:
        errors.append("remaining obligations changed, duplicated, or weakened")
    if set(data.get("self_review", {})) != {"circularity", "smuggled_architecture", "equivalence_rigging", "hidden_state_or_oracle", "reconstructability_vs_necessity", "bounded_vs_universal"}:
        errors.append("mandatory self-review is incomplete")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    data = json.loads(OBJECT.read_text())
    errors = validate(data)
    expected = render(data)
    if args.write: REPORT.write_text(expected)
    elif not REPORT.exists() or REPORT.read_text() != expected: errors.append("generated report is stale; run validator with --write")
    if errors: raise SystemExit("\n".join(f"ERROR: {x}" for x in errors))
    print("FARA-ARCH-W3-001 valid: 10 families; 6 dimensions; bounded result; counterexample retained")
    return 0


if __name__ == "__main__": raise SystemExit(main())
