#!/usr/bin/env python3
"""Validate frozen THM-TARGET-001 after bounded W4 and corpus-freeze closure."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DOC=ROOT/'docs/research/thm-target-001-v1.0.md'; TARGET=ROOT/'theory/evaluation/thm-target-001.json'; PREMISES=ROOT/'theory/evaluation/thm-target-001-premise-ledger.json'; GATES=ROOT/'theory/evaluation/research-gates.json'; CLAIMS=ROOT/'theory/evaluation/central-claim-registry.json'; LEMMA=ROOT/'theory/evaluation/s-core-construction-obstruction-ledger.json'; CORPUS=ROOT/'theory/evaluation/w3-5-corpus-freeze-result-v1.0.json'; PROOFS=[ROOT/f'theory/evaluation/s-core-w{i}-{name}.json' for i,name in [(0,'normalization-proof'),(1,'direct-axis-proof'),(2,'dynamics-history-proof'),(3,'global-witness-proof'),(4,'negative-control-proof')]]
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def main()->int:
    for p in (DOC,TARGET,PREMISES,GATES,CLAIMS,LEMMA,CORPUS,*PROOFS): assert p.is_file(),p
    text=DOC.read_text(encoding='utf-8')
    for phrase in ('Frozen prospective theorem target and premise boundary','Finite explicit core `S_core`','General extension class `S_IRD`','THM-CORE-REP-001','THM-IMP-001','This artifact does not establish'): assert phrase in text
    t=load(TARGET); assert t['theorem_target_id']=='THM-TARGET-001' and t['version']=='1.0'; assert t['status']=='frozen_unproved' and t['proof_status']=='partial_lemma_progress_only'; assert t['machine_check_status']=='bounded_executable_reference_only' and t['independent_review_status']=='not_started'; assert t['program_track']=='REP' and t['universal_structure_target']=='THM-US-TARGET-001'; assert set(t['source_classes'])=={'S_core','S_IRD'}; assert t['target_class']['id']=='A_FARA' and t['target_class']['adds_new_primitive'] is False; assert t['representation_witness']['tuple']==['E','D','M','iota','kappa']; assert t['w3_proof_registry']==PROOFS[3].relative_to(ROOT).as_posix(); assert t['w4_proof_registry']==PROOFS[4].relative_to(ROOT).as_posix()
    p=t['lemma_program']; assert p['status']=='w0_w1_w2_w3_w4_complete_w5_blocked_by_w3_5'; assert (p['total_obligations'],p['proved_obligations'],p['established_obstructions'],p['refuted_obstruction_hypotheses'],p['scope_boundaries_established'],p['open_obligations'])==(37,24,1,8,1,3); assert p['completed_waves']==['W0','W1','W2','W3','W4'] and p['active_wave']=='W5_blocked' and p['active_obligations']==[] and set(p['blocked_obligations'])=={'ASM-SC-001','ASM-SC-002','ASM-SC-003'}
    family={x['id']:x for x in t['theorem_family']}; assert all(x.get('status')!='proved' for x in family.values()); blockers=['specificity_discovery_bridge','theorem_assembly']; assert family['THM-CORE-COMMON-001']['blocked_by']==blockers; assert family['THM-CORE-REP-001']['blocked_by']==blockers; assert family['THM-IMP-001']['blocked_by']==blockers; assert t['next_required_artifact'].startswith('Evidence-backed W3.5'); assert t['w5_authorization']['authorized'] is False and t['w5_authorization']['blocked_by']==['W3.5-SDG-001'] and t['w5_authorization']['resolved_dependencies']==['OBS-SC-010']
    prem=load(PREMISES); assert prem['version']=='1.7'; progress=prem['proof_progress']; assert all(progress[x] is False for x in ('premise_change','source_scope_change','target_interface_change','theorem_status_change'))
    s=load(LEMMA)['execution_summary']; assert (s['proved'],s['obstruction_established'],s['scope_boundary_established'],s['refuted'],s['open'])==(24,1,1,8,3)
    assert [load(x)['proof_id'] for x in PROOFS]==['SCORE-W0-PROOF-001','SCORE-W1-PROOF-001','SCORE-W2-PROOF-001','SCORE-W3-PROOF-001','SCORE-W4-PROOF-001']
    corpus=load(CORPUS); assert corpus['status']=='complete' and corpus['artifact_id']=='RCS-CORPUS-001'; assert corpus['candidate_scoring_status']=='not_started'; assert corpus['claim_impact']['W5_authorized'] is False
    gates={x['name']:x for x in load(GATES)['gates']}; assert gates['formal-theorem-target']['status']=='satisfied'; assert gates['premise-ledger-and-semantics']['status']=='satisfied'; assert gates['faithful-representation-definition']['status']=='satisfied'; assert gates['formal-negative-controls']['status']=='satisfied'; assert gates['scoped-representation-proof']['status']=='not_satisfied' and gates['scoped-representation-proof']['evidence']==[]; assert gates['reasoning-contrast-scope-framework-frozen']['status']=='satisfied'; assert gates['reasoning-contrast-corpus-frozen']['status']=='satisfied' and gates['reasoning-contrast-corpus-frozen']['evidence']; assert gates['baseline-factorization-resolved']['status']=='not_satisfied'; assert gates['fara-specificity-resolved']['status']=='not_satisfied'; assert gates['reasoning-contrast-execution']['status']=='not_satisfied'; assert gates['universal-structure-result']['status']=='not_satisfied'
    for claim in load(CLAIMS)['claims']:
        if claim['id'] in {'CLM-EXISTENCE','CLM-UNIVERSALITY','CLM-UNIVERSAL-STRUCTURE','CLM-NECESSITY','CLM-MINIMALITY'}: assert claim['current_status'] not in {'supported','supported_at_registered_control_scope'}
    print('THM-TARGET-001 validation: PASS (W4 and corpus freeze complete; remaining evidence-backed W3.5 blocks W5; theorem unproved)'); return 0
if __name__=='__main__': raise SystemExit(main())
