#!/usr/bin/env python3
"""Validate and render the frozen FARA W1 primitive-independence execution."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "theory/evaluation/fara-w1-primitive-independence.json"
PRIMITIVES = ROOT / "frameworks/FARA/primitives.md"
DEFINITIONS = ROOT / "theory/definitions/definitions.md"

# W1 evaluated this exact historical seven-candidate set. Later scoped reductions
# must not rewrite the frozen execution or make it depend on the current registry.
EXPECTED = [
    "Object",
    "Property",
    "Relation",
    "Representation",
    "Interpretation",
    "Investigation",
    "Reasoning Calculus",
]
CURRENT_EXPECTED = [
    "Object",
    "Relation",
    "Representation",
    "Interpretation",
    "Reasoning Calculus",
]
ALLOWED = {"independent", "derivable", "equivalent", "unresolved"}


def section(text: str, heading: str) -> str:
    match = re.search(
        rf"^(#+) {re.escape(heading)}\n(.*?)(?=^#{{1,2}} |\Z)",
        text,
        re.M | re.S,
    )
    if not match:
        raise ValueError(f"missing canonical section: {heading}")
    return match.group(2).strip()


def validate(data: dict) -> None:
    current = re.findall(
        r"^- (.+)$",
        section(PRIMITIVES.read_text(), "Current Candidate Primitives"),
        re.M,
    )
    if current != CURRENT_EXPECTED:
        raise ValueError(f"current primitive-registry drift: {current!r}")
    if data.get("primitive_set") != EXPECTED:
        raise ValueError(
            f"frozen W1 primitive-set drift: {data.get('primitive_set')!r}"
        )
    if "neither can be derived from the other" not in section(
        DEFINITIONS.read_text(), "Independence"
    ):
        raise ValueError("canonical binary independence criterion drift")
    if "specified scope and objective" not in section(
        DEFINITIONS.read_text(), "Reduction"
    ):
        raise ValueError("canonical reduction criterion drift")
    results = data.get("results", [])
    if [row.get("primitive") for row in results] != EXPECTED:
        raise ValueError(
            "results must cover each primitive exactly once in frozen W1 order"
        )
    for row in results:
        if row.get("classification") not in ALLOWED:
            raise ValueError(f"invalid classification for {row.get('primitive')}")
        for key in (
            "attempt",
            "exact_blocker",
            "dependency_observation",
            "assumptions_used",
        ):
            if key not in row or row[key] in (None, ""):
                raise ValueError(f"missing {key} for {row.get('primitive')}")
        if row["classification"] == "unresolved" and row["assumptions_used"]:
            raise ValueError(
                f"unresolved result silently introduces assumptions: {row['primitive']}"
            )
    if any(row["classification"] != "unresolved" for row in results):
        raise ValueError(
            "positive classification requires a separately registered formal proof/countermodel validator"
        )
    findings = data.get("adversarial_findings", {})
    for key in (
        "circular_reasoning",
        "hidden_equivalent_candidates",
        "renamed_duplicates",
        "downstream_dependency",
    ):
        if key not in findings:
            raise ValueError(f"missing adversarial audit: {key}")
    forbidden = re.compile(r"frameworks/(?:FAR|FARO)/", re.I)
    proof_inputs = json.dumps([data["criterion"], data["shared_blockers"], results])
    if forbidden.search(proof_inputs):
        raise ValueError(
            "downstream FAR/FARO artifact used in criterion, blocker, or primitive result"
        )


def render(data: dict) -> str:
    rows = []
    for row in data["results"]:
        assumptions = ", ".join(row["assumptions_used"]) or "None"
        rows.append(
            f"| {row['primitive']} | **{row['classification']}** | "
            f"{row['attempt']} **Blocker:** {row['exact_blocker']} | {assumptions} |"
        )
    return """# FARA W1 Primitive-Independence Result

> Generated by `python tools/check_fara_primitive_independence.py --write`; do not edit manually.

**Status:** Historical Research — complete execution; all outcomes unresolved under the frozen W1 contract.

## Authority and criterion

W1 evaluated the frozen historical candidate set **Object, Property, Relation, Representation, Interpretation, Investigation, Reasoning Calculus**. The current Project FAR v1.0 registry is maintained separately in `frameworks/FARA/primitives.md`; later scoped reductions do not retroactively alter this execution. Canonical `Independence` is binary, while canonical `Reduction` requires a specified scope and objective. For the requested joint test, a primitive is independent only given a countermodel to its definability from the other six in an explicitly stated formal theory; it is derivable only given a complete lossless definition from the other six; it is equivalent only given both reductions under a stated equivalence relation. Otherwise it is unresolved.

## Per-primitive adjudication

| Primitive | Result | Exact attempt, evidence, or blocker | Assumptions used |
|---|---|---|---|
""" + "\n".join(rows) + """

## Adversarial review

- **Circularity:** Object ← Representation ← Object; Representation ↔ Interpretation; Investigation ↔ Reasoning Calculus. These are dependency hazards, not proofs of equivalence.
- **Hidden-equivalent candidates:** Property as unary Relation; Relation as Property of tuples; Interpretation as Relation/mapping; Representation as interpreted Object. Each needed unregistered machinery or an equivalence relation under the frozen W1 contract and therefore remained unproved there.
- **Renamed duplicates:** no exact normalized duplicate was found. Semantic duplicate detection was blocked by the absent equivalence relation.
- **Downstream leakage:** no FAR or FARO methodology is an assumption. Downstream operations cannot prove FARA primitive independence.

## Consequence

W1 supplies no positive independence theorem: every frozen W1 outcome is **unresolved** and cannot support FARA minimality, necessity, irreducibility, or universality. `FARA-CANONICAL-KERNEL-001` later supplies scoped reductions for Property and Investigation under a new explicit formal contract; that later result supersedes current registry status without rewriting W1 history.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    data = json.loads(DATA.read_text())
    validate(data)
    output = ROOT / data["generated_artifact"]
    expected = render(data)
    if args.write:
        output.write_text(expected)
    elif not output.exists() or output.read_text() != expected:
        raise SystemExit("generated FARA W1 result is stale; run with --write")
    print("FARA W1 primitive-independence validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
