#!/usr/bin/env python3
"""Validate preserved FARA W1 evidence and its terminal reclassification."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "theory/evaluation/fara-w1-primitive-independence.json"
PRIMITIVES = ROOT / "frameworks/FARA/primitives.md"
DEFINITIONS = ROOT / "theory/definitions/definitions.md"
EXPECTED = ["Object", "Property", "Relation", "Representation", "Interpretation", "Investigation", "Reasoning Calculus"]
ALLOWED = {"independent", "derivable", "equivalent", "unresolved"}
CORE = ROOT / "theory/theorems/Project-FAR-Theory-Closure-v1.0.md"


def section(text: str, heading: str) -> str:
    match = re.search(rf"^(#+) {re.escape(heading)}\n(.*?)(?=^#{{1,2}} |\Z)", text, re.M | re.S)
    if not match:
        raise ValueError(f"missing canonical section: {heading}")
    return match.group(2).strip()


def schema_roles(text: str) -> list[str]:
    body = section(text, "Current schema and contract roles")
    roles = re.findall(r"^\| ([^|]+?) \| [^|]+ \|$", body, re.M)
    return [role.strip() for role in roles if role.strip() != "Role"]


def validate(data: dict) -> None:
    primitive_text = PRIMITIVES.read_text()
    canonical = schema_roles(primitive_text)
    if canonical != EXPECTED or data.get("primitive_set") != canonical:
        raise ValueError(f"schema-role drift: canonical={canonical!r}, result={data.get('primitive_set')!r}")
    if "not global primitives" not in primitive_text:
        raise ValueError("terminal schema-role boundary missing")
    if "global primitive-independence and primitive-minimality search is closed" not in primitive_text:
        raise ValueError("terminal primitive-search closure missing")
    if "FAR-CORE-007" not in CORE.read_text():
        raise ValueError("terminal reclassification authority missing")
    independence = section(DEFINITIONS.read_text(), "Independence")
    if "relative to a stated theory and derivability regime" not in independence:
        raise ValueError("contract-relative independence criterion drift")
    if "invariance under the admitted re-representations" not in independence:
        raise ValueError("representation-independence boundary drift")
    reduction = section(DEFINITIONS.read_text(), "Reduction")
    if "specified contract, scope, and objective" not in reduction:
        raise ValueError("contract-relative reduction criterion drift")
    results = data.get("results", [])
    if [row.get("primitive") for row in results] != canonical:
        raise ValueError("results must cover each primitive exactly once in canonical order")
    for row in results:
        if row.get("classification") not in ALLOWED:
            raise ValueError(f"invalid classification for {row.get('primitive')}")
        for key in ("attempt", "exact_blocker", "dependency_observation", "assumptions_used"):
            if key not in row or row[key] in (None, ""):
                raise ValueError(f"missing {key} for {row.get('primitive')}")
        if row["classification"] == "unresolved" and row["assumptions_used"]:
            raise ValueError(f"unresolved result silently introduces assumptions: {row['primitive']}")
    if any(row["classification"] != "unresolved" for row in results):
        raise ValueError("positive classification requires a separately registered formal proof/countermodel validator")
    findings = data.get("adversarial_findings", {})
    for key in ("circular_reasoning", "hidden_equivalent_candidates", "renamed_duplicates", "downstream_dependency"):
        if key not in findings:
            raise ValueError(f"missing adversarial audit: {key}")
    forbidden = re.compile(r"frameworks/(?:FAR|FARO)/", re.I)
    proof_inputs = json.dumps([data["criterion"], data["shared_blockers"], results])
    if forbidden.search(proof_inputs):
        raise ValueError("downstream FAR/FARO artifact used in criterion, blocker, or primitive result")


def render(data: dict) -> str:
    rows = []
    for r in data["results"]:
        assumptions = ", ".join(r["assumptions_used"]) or "None"
        rows.append(f"| {r['primitive']} | **{r['classification']}** | {r['attempt']} **Blocker:** {r['exact_blocker']} | {assumptions} |")
    return """# FARA W1 Primitive-Independence Result

> Generated by `python tools/check_fara_primitive_independence.py --write`; do not edit manually.

**Status:** Historical research evidence — complete execution; all outcomes were unresolved at execution time. Current-status implications are superseded by `PROJECT-FAR-CORE-THEORY-1.0`.

## Historical authority and criterion

The frozen candidate set was **Object, Property, Relation, Representation, Interpretation, Investigation, Reasoning Calculus**. The current `frameworks/FARA/primitives.md` retains those names as schema and contract roles, not global primitives. At execution time, canonical `Independence` was binary, while canonical `Reduction` required a specified scope and objective. For that joint test, a candidate was independent only given a countermodel to its definability from the other six in an explicitly stated formal theory; it was derivable only given a complete lossless definition from the other six; it was equivalent only given both reductions under a stated equivalence relation. Otherwise it was unresolved.

## Per-primitive adjudication

| Primitive | Result | Exact attempt, evidence, or blocker | Assumptions used |
|---|---|---|---|
""" + "\n".join(rows) + """

## Adversarial review

- **Circularity:** Object ← Representation ← Object; Representation ↔ Interpretation; Investigation ↔ Reasoning Calculus. These are dependency hazards, not proofs of equivalence.
- **Hidden-equivalent candidates:** Property as unary Relation; Relation as Property of tuples; Interpretation as Relation/mapping; Representation as interpreted Object. Each needs unregistered machinery or an equivalence relation and therefore remains unproved.
- **Renamed duplicates:** no exact normalized duplicate was found. Semantic duplicate detection is blocked by the absent equivalence relation.
- **Downstream leakage:** no FAR or FARO methodology is an assumption. Downstream operations cannot prove FARA primitive independence.

## Terminal reclassification

W1 remains valid evidence that the original deletion-style attempt supplied no positive independence theorem. It does not define the current research queue. Under `FAR-CORE-007`, faithful reification, tagging, splitting, and combination make primitive and operator counts representation-dependent unless a comparison contract fixes the language, equivalence, and cost order. The seven names are therefore schema or contract roles. The contract-free global primitive-independence/minimality search is closed; scoped implementation-cost or domain-necessity questions require an explicit contract.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    data = json.loads(DATA.read_text())
    validate(data)
    output = ROOT / data["generated_artifact"]
    expected = render(data)
    if args.write:
        output.write_text(expected)
    elif not output.exists() or output.read_text() != expected:
        raise SystemExit("generated FARA W1 result is stale; run with --write")
    print("FARA W1 primitive-independence validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
