#!/usr/bin/env python3
"""Validate and exhaustively replay FARA-OPS-W2-001's finite model."""
from __future__ import annotations
import argparse, itertools, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
PROOF = ROOT / "theory/evaluation/fara-operator-w2-proof-v1.0.json"
GENERATED = ROOT / "theory/evaluation/generated-fara-operator-w2-summary.md"
AUTHORITY = ROOT / "docs/glossary/canonical-terminology.md"
NAMES = ("Construct", "Differentiate", "Restrict")
COORD = {"Construct": "R", "Differentiate": "D", "Restrict": "A"}
EFFECT = {"Construct": "add", "Differentiate": "add", "Restrict": "remove"}
EXPECTED_STATUS = "coordinate_separation_induced_bounded_minimality_global_unresolved"
EXPECTED_MODEL = "finite_coordinate_trace_v1"
EXPECTED_CLAIM = "Under the operator-separating coordinate premises of finite_coordinate_trace_v1, Construct, Differentiate, and Restrict are jointly sufficient and individually irreducible under componentwise observational equivalence. The minimality result is induced by those premises and does not establish canonical or global operator necessity."
EXPECTED_STRONGEST = "coordinate-separation-induced bounded minimality for finite_coordinate_trace_v1 only"
EXPECTED_NONCLAIMS = {"global sufficiency","global irreducibility","unique basis","metaphysical necessity","FARA primitive minimality","Resolve derivability","Select derivability","canonical operator necessity","minimality independent of coordinate separation"}
EXPECTED_OBLIGATIONS = {
    "Freeze canonical transition semantics independently of this evaluation.",
    "Freeze an admissible open-world candidate universe and equivalence/cost preorder.",
    "Model declared-rule representation and rule execution before adjudicating Resolve or Select.",
    "Determine whether interpretation, observation, deletion, relaxation, or quotient/merge effects belong to the intended operator scope.",
    "Supply lower bounds that do not assume coordinate locality if a stronger claim is sought.",
}
EXPECTED_CANDIDATES = {
    "Resolve": "outside_scope_unresolved", "Select": "outside_scope_unresolved",
    "Transform": "composition_in_scope", "Compare": "representation_convenience",
    "Interpret": "outside_scope_unresolved", "Observe": "outside_scope_unresolved",
    "Delete_or_relax": "outside_scope_counterexample", "Merge": "outside_scope_unresolved",
}

def apply(state, operator, token):
    out = {key: frozenset(value) for key, value in state.items()}
    coordinate = COORD[operator]
    if EFFECT[operator] == "add": out[coordinate] = out[coordinate] | {token}
    else: out[coordinate] = out[coordinate] - {token}
    return out

def render(data):
    rows = "\n".join(f"| {o['name']} | {o['status']} | {o['elimination']} | {o['derivation']} |" for o in data["operators"])
    candidates = "\n".join(f"| {c['name']} | {c['classification']} |" for c in data["fourth_candidates"])
    return f"""<!-- Generated by tools/check_fara_operator_w2.py; do not edit. -->
# FARA operator W2 generated summary

Status: `{data['status']}`

The bounded minimality result is induced by the model's operator-separating coordinate premises. It is not evidence of canonical or global operator necessity.

| Operator | Status | Elimination | Derivation |
|---|---|---|---|
{rows}

## Fourth-candidate search

| Candidate | Classification |
|---|---|
{candidates}

**Strongest claim:** {data['strongest_claim']}.

**Global claim:** {data['global_claim']}.
"""

def validate(data):
    errors=[]
    cells = [[cell.strip() for cell in line.strip().strip("|").split("|")] for line in AUTHORITY.read_text().splitlines() if line.startswith("| ")]
    expected = {cell[0]: cell[1] for cell in cells if cell and cell[0] in NAMES}
    if data.get("schema_version") != "1.0": errors.append("schema version must remain 1.0")
    if data.get("id") != "FARA-OPS-W2-001": errors.append("theorem ID drifted")
    if data.get("status") != EXPECTED_STATUS: errors.append("status must preserve coordinate-separation-induced bounded scope")
    if data.get("authority",{}).get("operators") != expected: errors.append("canonical operator definitions drifted from glossary authority")
    model=data.get("bounded_model",{})
    if model.get("name") != EXPECTED_MODEL: errors.append("bounded model name drifted")
    if model.get("claim") != EXPECTED_CLAIM: errors.append("bounded model claim drifted or overclaimed")
    ops=data.get("operators",[])
    if [o.get("name") for o in ops] != list(NAMES): errors.append("operator set/order must be canonical")
    if {(o.get("name"),o.get("coordinate"),o.get("effect")) for o in ops} != {(n,COORD[n],EFFECT[n]) for n in NAMES}: errors.append("coordinate effects changed")
    expected_subsets=[list(s) for size in range(3) for s in itertools.combinations(NAMES,size)]
    if data.get("elimination_subsets_tested") != expected_subsets: errors.append("all seven proper subsets must be tested in canonical order")
    witnesses={w.get("requires"):w for w in data.get("witnesses",[])}
    for name in NAMES:
        if name not in witnesses: errors.append(f"missing witness for {name}"); continue
        w=witnesses[name]; start={k:frozenset(v) for k,v in w["start"].items()}; target={k:frozenset(v) for k,v in w["target"].items()}
        token=next(iter(target[COORD[name]] ^ start[COORD[name]]))
        if apply(start,name,token)!=target: errors.append(f"{name} witness is not realized")
        for length in range(4):
            for seq in itertools.product([n for n in NAMES if n != name], repeat=length):
                state=start
                for op in seq: state=apply(state,op,token)
                if state==target: errors.append(f"{name} derived by {seq}")
    actual_candidates={c.get("name"):c.get("classification") for c in data.get("fourth_candidates",[])}
    if actual_candidates != EXPECTED_CANDIDATES: errors.append("fourth-candidate classifications drifted")
    if data.get("strongest_claim") != EXPECTED_STRONGEST: errors.append("strongest claim drifted or overclaimed")
    if data.get("global_claim") != "unresolved": errors.append("global claim must remain unresolved")
    if set(data.get("nonclaims",[])) != EXPECTED_NONCLAIMS: errors.append("required nonclaims changed")
    if set(data.get("remaining_obligations",[])) != EXPECTED_OBLIGATIONS: errors.append("required obligations changed")
    return errors

def main():
    parser=argparse.ArgumentParser(); parser.add_argument("--write",action="store_true"); args=parser.parse_args()
    data=json.loads(PROOF.read_text()); errors=validate(data); generated=render(data)
    if args.write: GENERATED.write_text(generated)
    elif not GENERATED.exists() or GENERATED.read_text()!=generated: errors.append("generated summary is stale; run with --write")
    if errors: raise SystemExit("\n".join(f"ERROR: {e}" for e in errors))
    print("FARA-OPS-W2-001 valid: 3 witnesses, 7 eliminations, 8 fourth candidates")
if __name__ == "__main__": main()
