#!/usr/bin/env python3
"""Evaluate FAR reasoning-system fixtures against the falsification harness."""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List

from parse_far import load_far_yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FIXTURE_DIR = ROOT / "examples" / "far" / "reasoning-systems"

VALID_CLASSIFICATIONS = {
    "fits FAR",
    "extends FAR",
    "candidate counterexample",
    "fails fixture",
}

VERDICT_TO_CLASSIFICATION = {
    "fits FAR": "fits FAR",
    "extends FAR": "extends FAR",
    "falsifies FAR": "candidate counterexample",
    "candidate counterexample": "candidate counterexample",
}

REQUIRED_PRIMITIVES = [
    "Investigation",
    "Representation",
    "Representational Structure",
    "Interpretation",
    "Reasoning Calculus",
]


@dataclass
class ReasoningSystemResult:
    fixture: str
    system: str
    classification: str
    primitive_mapping_complete: bool
    representations: int
    relations: int
    transitions: int
    cycles: int
    notes: List[str]

    def to_row(self) -> str:
        complete = "yes" if self.primitive_mapping_complete else "no"
        notes = "; ".join(self.notes) if self.notes else "-"
        return (
            f"| {self.system} | `{self.fixture}` | {self.classification} | "
            f"{complete} | {self.representations} | {self.relations} | "
            f"{self.transitions} | {self.cycles} | {notes} |"
        )


def primitive_mapping_complete(mapping: Any) -> bool:
    if mapping is None:
        return False
    return all(
        bool(getattr(mapping, field))
        for field in ["investigation", "representation", "structure", "interpretation", "calculus"]
    )


def classify_fixture(path: Path) -> ReasoningSystemResult:
    fixture_name = str(path.relative_to(ROOT)) if path.is_absolute() else str(path)
    try:
        far = load_far_yaml(path)
        errors = far.validate_well_formed()
    except Exception as exc:
        return ReasoningSystemResult(
            fixture=fixture_name,
            system=path.stem,
            classification="fails fixture",
            primitive_mapping_complete=False,
            representations=0,
            relations=0,
            transitions=0,
            cycles=0,
            notes=[f"parse failure: {exc}"],
        )

    notes: List[str] = []
    if errors:
        return ReasoningSystemResult(
            fixture=fixture_name,
            system=far.reasoning_system.system if far.reasoning_system else path.stem,
            classification="fails fixture",
            primitive_mapping_complete=primitive_mapping_complete(far.reasoning_system),
            representations=len(far.representations),
            relations=len(far.relations),
            transitions=len(far.transitions),
            cycles=len(far.detect_cycles()),
            notes=[f"validation failure: {error}" for error in errors],
        )

    if far.reasoning_system is None:
        classification = "fails fixture"
        system = path.stem
        notes.append("missing reasoning_system mapping")
    else:
        system = far.reasoning_system.system
        classification = VERDICT_TO_CLASSIFICATION.get(far.reasoning_system.verdict, "fails fixture")
        if classification == "fails fixture":
            notes.append(f"unsupported verdict: {far.reasoning_system.verdict}")

    complete = primitive_mapping_complete(far.reasoning_system)
    if not complete:
        notes.append("primitive mapping incomplete")

    cycles = far.detect_cycles()
    if cycles:
        notes.append("dependency cycle detected")

    return ReasoningSystemResult(
        fixture=fixture_name,
        system=system,
        classification=classification,
        primitive_mapping_complete=complete,
        representations=len(far.representations),
        relations=len(far.relations),
        transitions=len(far.transitions),
        cycles=len(cycles),
        notes=notes,
    )


def find_fixtures(root: Path) -> List[Path]:
    return sorted(root.glob("*.far.yaml"))


def render_markdown(results: List[ReasoningSystemResult]) -> str:
    counts: Dict[str, int] = {classification: 0 for classification in sorted(VALID_CLASSIFICATIONS)}
    for result in results:
        counts[result.classification] = counts.get(result.classification, 0) + 1

    lines = [
        "# Reasoning-System Evaluation Summary",
        "",
        "Status: Generated by `tools/evaluate_reasoning_systems.py`.",
        "",
        "## Classification counts",
        "",
        "| Classification | Count |",
        "|---|---:|",
    ]
    for classification in ["fits FAR", "extends FAR", "candidate counterexample", "fails fixture"]:
        lines.append(f"| {classification} | {counts.get(classification, 0)} |")

    lines.extend([
        "",
        "## Fixture results",
        "",
        "| System | Fixture | Classification | Primitive mapping complete | Representations | Relations | Transitions | Cycles | Notes |",
        "|---|---|---|---|---:|---:|---:|---:|---|",
    ])
    lines.extend(result.to_row() for result in results)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate FAR reasoning-system fixtures")
    parser.add_argument("--fixtures", type=Path, default=DEFAULT_FIXTURE_DIR)
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON results")
    parser.add_argument("--output", type=Path, help="write Markdown summary to this path")
    args = parser.parse_args()

    fixtures = find_fixtures(args.fixtures)
    if not fixtures:
        print(f"No reasoning-system fixtures found in {args.fixtures}")
        return 1

    results = [classify_fixture(path) for path in fixtures]

    if args.json:
        payload = {
            "valid_classifications": sorted(VALID_CLASSIFICATIONS),
            "results": [asdict(result) for result in results],
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        summary = render_markdown(results)
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(summary, encoding="utf-8")
        print(summary)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
