#!/usr/bin/env python3
"""Evaluate the Project FAR primitive-sufficiency evidence registry."""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = ROOT / "theory" / "evaluation" / "evidence-registry.yaml"

REQUIRED_FIELDS = [
    "id",
    "system",
    "fixture",
    "classification",
    "analysis_status",
    "registry_resolution",
    "confidence",
    "review_status",
    "notes",
]

UNRESOLVED_RESOLUTIONS = {"unresolved"}
COUNTEREXAMPLE_CLASSIFICATIONS = {"candidate counterexample"}
COUNTEREXAMPLE_RESOLUTIONS = {"real counterexample", "falsification", "requires sixth primitive"}


def load_registry(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle)
    if not isinstance(payload, dict):
        raise ValueError("registry root must be a mapping")
    entries = payload.get("entries")
    if not isinstance(entries, list):
        raise ValueError("registry must contain an entries list")
    return entries


def validate_entries(entries: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []
    seen_ids: set[str] = set()
    for index, entry in enumerate(entries, start=1):
        if not isinstance(entry, dict):
            errors.append(f"entry {index} must be a mapping")
            continue
        label = entry.get("id", f"entry {index}")
        for field in REQUIRED_FIELDS:
            if field not in entry or entry[field] in (None, ""):
                errors.append(f"{label}: missing required field {field}")
        entry_id = entry.get("id")
        if isinstance(entry_id, str):
            if entry_id in seen_ids:
                errors.append(f"{entry_id}: duplicate id")
            seen_ids.add(entry_id)
        fixture = entry.get("fixture")
        if isinstance(fixture, str) and not (ROOT / fixture).exists():
            errors.append(f"{label}: fixture does not exist: {fixture}")
    return errors


def markdown_list(entries: list[dict[str, Any]]) -> list[str]:
    if not entries:
        return ["- None"]
    return [f"- {entry['id']}: {entry['system']} (`{entry['fixture']}`)" for entry in entries]


def render_report(entries: list[dict[str, Any]], validation_errors: list[str]) -> str:
    classification_counts = Counter(entry["classification"] for entry in entries)
    analysis_counts = Counter(entry["analysis_status"] for entry in entries)
    unresolved = [entry for entry in entries if entry["registry_resolution"] in UNRESOLVED_RESOLUTIONS]
    candidate_counterexamples = [
        entry
        for entry in entries
        if entry["classification"] in COUNTEREXAMPLE_CLASSIFICATIONS
        or entry["registry_resolution"] in COUNTEREXAMPLE_RESOLUTIONS
    ]

    lines = [
        "# Primitive Sufficiency Evaluation Report",
        "",
        "Status: Generated by `tools/evaluate_primitive_sufficiency.py` from `theory/evaluation/evidence-registry.yaml`.",
        "",
        "## Registry validation",
        "",
    ]
    if validation_errors:
        lines.extend(f"- ERROR: {error}" for error in validation_errors)
    else:
        lines.append("- No registry validation errors detected.")

    lines.extend([
        "",
        "## Classification counts",
        "",
        "| Classification | Count |",
        "|---|---:|",
    ])
    for classification, count in sorted(classification_counts.items()):
        lines.append(f"| {classification} | {count} |")

    lines.extend([
        "",
        "## Analysis outcome counts",
        "",
        "| Analysis outcome | Count |",
        "|---|---:|",
    ])
    for outcome, count in sorted(analysis_counts.items()):
        lines.append(f"| {outcome} | {count} |")

    lines.extend([
        "",
        "## Unresolved cases",
        "",
        *markdown_list(unresolved),
        "",
        "## Candidate counterexamples",
        "",
        *markdown_list(candidate_counterexamples),
        "",
        "## Summary metrics",
        "",
        f"- Total systems evaluated: {len(entries)}",
        f"- Systems fitting FAR: {classification_counts.get('fits FAR', 0)}",
        f"- Systems requiring conservative extension: {analysis_counts.get('conservative extension', 0)}",
        f"- Systems outside scope: {analysis_counts.get('outside FAR scope', 0) + analysis_counts.get('outside scope', 0)}",
        f"- Candidate counterexamples: {len(candidate_counterexamples)}",
        f"- Unresolved cases: {len(unresolved)}",
        "",
        "## Current conclusion",
        "",
        "No analyzed v0.2.0 case currently requires a sixth primitive, but this is provisional.",
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate primitive-sufficiency evidence registry")
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--output", type=Path, help="write Markdown report to this path")
    args = parser.parse_args()

    entries = load_registry(args.registry)
    errors = validate_entries(entries)
    report = render_report(entries, errors)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8")
    print(report, end="")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
