#!/usr/bin/env python3
"""Generate the canonical investigation execution index."""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "research/validation/generated-investigation-index.md"


def render() -> str:
    rows = []
    for path in sorted((ROOT / "research/validation/executions").glob("*.execution.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        steps = data["required_steps"]
        completed = sum(str(step["status"]).lower() in {"complete", "completed"} for step in steps)
        rows.append(f"| {data['investigation']} | {data['status']} | {data['result']} | {completed}/{len(steps)} | `{path.relative_to(ROOT)}` |")
    return "\n".join([
        "# Investigation Execution Index",
        "",
        "Generated by `python tools/generate_investigation_index.py` from execution manifests. Do not edit manually.",
        "",
        "| Investigation | Lifecycle status | Result | Required steps complete | Execution manifest |",
        "|---|---|---|---:|---|",
        *rows,
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated artifact: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("Investigation execution index: current")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
