#!/usr/bin/env python3
"""Generate an advisory Project FAR status report from existing evidence files."""
from __future__ import annotations

from collections import Counter
from pathlib import Path
import re
import yaml
from report_link_utils import markdown_link

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/reports/project-status-generated.md"
REGISTRIES = {
    "evidence": ROOT / "theory/evaluation/evidence-registry.yaml",
    "external": ROOT / "theory/evaluation/external-validation-registry.yaml",
    "adversarial": ROOT / "theory/falsification/adversarial-test-suite.yaml",
    "pressure": ROOT / "theory/falsification/primitive-pressure-registry.yaml",
}
REPORTS = [
    "docs/governance/deduction-first-research-standard.md",
    "docs/planning/deduction-first-proof-roadmap.md",
    "docs/planning/architecture-neutral-research-roadmap.md",
    "docs/research/thm-target-001-v1.0.md",
    "theory/evaluation/thm-target-001.json",
    "theory/evaluation/thm-target-001-premise-ledger.json",
    "docs/audits/deduction-first-research-shift-audit.md",
    "docs/reports/primitive-sufficiency-report.md",
    "docs/reports/external-validation-report.md",
    "docs/reports/project-far-v0.3.0-synthesis.md",
    "theory/evaluation/comparative-representation/experiments/CRE-001/deterministic-verifier/README.md",
    "theory/evaluation/comparative-representation/experiments/CRE-001/deterministic-verifier/cre001-deterministic-comparison.json",
    "theory/evaluation/comparative-representation/experiments/CRE-002/execution/cre002-comparison.json",
    "theory/evaluation/comparative-representation/experiments/CRE-002-EXT-001/execution/cre002-ext001-comparison.json",
    "docs/reports/cre002-ext001-evidence-analysis.md",
]


def load_yaml(path: Path):
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def entries(data):
    return data.get("entries") or data.get("tests") or []


def latest_release():
    versions = []
    for p in (ROOT / "docs/releases").glob("project-far-v*.md"):
        m = re.search(r"v(\d+\.\d+\.\d+)", p.name)
        if m:
            versions.append((tuple(int(x) for x in m.group(1).split(".")), m.group(0), p))
    return max(versions)[2] if versions else None


def count_values(items, key):
    return Counter(str(i.get(key, "unspecified")) for i in items)


def bullet_counts(counter):
    return "\n".join(f"- {k}: {v}" for k, v in sorted(counter.items())) or "- None found."


def nav_links(out_path: Path) -> list[str]:
    return [
        f"- README Command Center: {markdown_link(ROOT / 'README.md', out_path)}",
        f"- Project Status: {markdown_link(ROOT / 'docs/reports/project-status-generated.md', out_path)}",
        f"- Research Gaps: {markdown_link(ROOT / 'docs/reports/research-gap-report.md', out_path)}",
        f"- Next Actions: {markdown_link(ROOT / 'docs/planning/next-actions.md', out_path)}",
    ]


def main() -> int:
    data = {name: load_yaml(path) for name, path in REGISTRIES.items()}
    ev = entries(data["evidence"])
    ext = entries(data["external"])
    adv = entries(data["adversarial"])
    pressure = data["pressure"].get("primitives", [])
    unresolved = [e for e in ev + ext + adv if "unresolved" in str(e.get("registry_resolution", e.get("current_status", ""))).lower()]
    failures = []
    for p in pressure:
        failures.extend(p.get("candidate_primitive_failures") or [])
    conclusion = (
        "CRE-002-EXT-001 remains a prospective bounded result under Vocabulary Semantics Baseline 1.1 and does not establish "
        "primitive-only or universal sufficiency, necessity, minimality, independence, superiority, a FAR proof, a universal "
        "reasoning structure, or independent replication. THM-TARGET-001 is now frozen as an unproved theorem family with an "
        "explicit S_core scope, broader S_IRD extension target, theorem-facing FARA package, premise ledger, P1-P7 obligations, "
        "and unresolved P8 parameter. The immediate formal work is faithful-representation semantics and P8 resolution."
    )
    lines = [
        "# Project Status (Generated)", "", "## Navigation", "", *nav_links(OUT), "",
        "Generated by `python tools/project_status_report.py` from machine-readable registries and selected reports.", "",
        "This report uses cautious language and does not authorize theory changes.", "",
        "## Current Research Mode", "",
        "- Primary mode: deduction-first with parallel empirical validation.",
        "- Frozen central artifact: `THM-TARGET-001` v1.0 and its premise ledger.",
        "- Immediate central work: formalize `Pres_1` through `Pres_7` and `Faithful_m8`, then resolve P8.",
        "- Formal-theorem-target gate: satisfied with registered artifacts.",
        "- Premise-ledger-and-semantics gate: in progress.",
        "- Parallel supporting track: PBTS-001 replication, comparative evaluation, boundary discovery, and implementation validation.",
        "- Current theorem status: no representation theorem, universality theorem, necessity theorem, or minimality theorem is established.", "",
        "## Source Registries", "",
        *[f"- {name}: {markdown_link(path, OUT)}" for name, path in REGISTRIES.items()], "",
        "## Current Release Baseline", "",
        f"- Latest release document detected: {markdown_link(latest_release(), OUT) if latest_release() else 'unknown'}", "",
        "## Evaluation Counts", "",
        f"- Internal reasoning systems evaluated: {len(ev)}",
        f"- External systems evaluated: {len(ext)}",
        f"- Adversarial tests summarized: {len(adv)}", "",
        "## Current Classification Counts", "", "### Internal registry", "", bullet_counts(count_values(ev, "classification")), "",
        "### External validation registry", "", bullet_counts(count_values(ext, "classification")), "",
        "### Adversarial test status", "", bullet_counts(count_values(adv, "current_status")), "",
        "## Unresolved Cases", "",
    ]
    lines += [f"- `{e.get('id','unknown')}`: {e.get('system') or e.get('title')} ({e.get('registry_resolution') or e.get('current_status')})" for e in unresolved] or ["- None detected in parsed status fields."]
    lines += ["", "## Candidate Primitive Failures", ""]
    lines += [f"- {x}" for x in failures] or ["- None recorded in the primitive pressure registry."]
    lines += ["", "## Current Primitive Pressure Summary", ""]
    for p in pressure:
        lines.append(f"- **{p.get('primitive')}**: {p.get('number_of_tests_stressing_it', 0)} stressing tests; unresolved pressures: {len(p.get('unresolved_pressures') or [])}; assessment: {p.get('current_assessment','not stated')}")
    lines += [
        "", "## Comparative Representation Status", "",
        "CRE-001: deterministic comparison complete at its registered retrospective scope under compiler-authored declared interpretations.", "",
        "CRE-002: prospective semantic-licensing result complete under Baseline 1.0; all three candidates remain unsupported because the five required capability classes were not licensed.", "",
        "CRE-002-EXT-001: prospective bounded execution complete under Baseline 1.1; all three candidates are complete for the registered scenario, ambiguity policies, derived machinery, and verifier conditions.", "",
        "The extension does not rank the vocabularies and does not retroactively alter CRE-002.", "",
        "## Current Evidence Conclusion", "", conclusion, "", "## Relevant Reports", ""
    ]
    for r in REPORTS:
        lines.append(f"- {markdown_link(ROOT / r, OUT)}" if (ROOT / r).exists() else f"- Missing expected report: `{r}`")
    lines += ["", "## Navigation", "", *nav_links(OUT)]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
