#!/usr/bin/env python3
"""Generate the separated REP, ADJ, and USD Project FAR status report."""
from __future__ import annotations
import json
from pathlib import Path
from report_link_utils import markdown_link

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/reports/project-status-generated.md'
LEDGER=ROOT/'theory/evaluation/s-core-construction-obstruction-ledger.json'
W35=ROOT/'theory/evaluation/w3-5-specificity-and-discovery-gate.json'
SCOPE=ROOT/'theory/evaluation/reasoning-and-contrast-scope-v1.0.json'
CANDIDATES=ROOT/'theory/evaluation/universal-structure-candidate-registry.json'
REPORTS=[
('Central Research Program','docs/governance/central-research-program.md'),
('Representation–Discovery Separation Standard','docs/governance/representation-discovery-separation-standard-v1.0.md'),
('Deduction-First Proof Roadmap','docs/planning/deduction-first-proof-roadmap.md'),
('Architecture-Neutral Research Roadmap','docs/planning/architecture-neutral-research-roadmap.md'),
('Generic Relational Baseline','docs/research/generic-relational-baseline-v1.0.md'),
('Reasoning and Contrast Scope','docs/research/reasoning-and-contrast-scope-v1.0.md'),
('Universal-Structure Discovery Target','docs/research/universal-structure-discovery-target-v1.0.md'),
('W3.5 Gate','docs/research/w3-5-specificity-and-discovery-gate-v1.0.md'),
]
def load(path): return json.loads(path.read_text(encoding='utf-8'))
def nav(): return [
 f"- README Command Center: {markdown_link(ROOT/'README.md',OUT)}",
 f"- Project Status: {markdown_link(OUT,OUT)}",
 f"- Research Gaps: {markdown_link(ROOT/'docs/reports/research-gap-report.md',OUT)}",
 f"- Next Actions: {markdown_link(ROOT/'docs/planning/next-actions.md',OUT)}",
]
def main()->int:
    ledger=load(LEDGER); summary=ledger['execution_summary']; w35=load(W35); scope=load(SCOPE); candidates=load(CANDIDATES)
    lines=['# Project Status (Generated)','','## Navigation','',*nav(),'','Generated by `python tools/project_status_report.py` from the canonical REP, ADJ, and USD registries.','','## Current Research Mode','',
    '- Primary mode: deduction-first with separated REP, ADJ, and USD tracks.',
    '- REP status: W0–W3 complete as project-authored finite construction packages; W4 active.',
    f"- ADJ status: W3.5 `{w35['status']}`; factorization unresolved.",
    '- USD status: `THM-US-TARGET-001` frozen prospectively; no candidate result.',
    '- W5 status: blocked by `OBS-SC-010` and `W3.5-SDG-001`.',
    '- Representation progress does not update universal-structure, necessity, or minimality status.',
    '- Mechanized-proof-verification gate: not satisfied.',
    '- Independent-proof-review gate: not satisfied.','','## REP Ledger','',
    f"- Registered obligations: {summary['total']}",
    f"- Project-authored proved construction lemmas: {summary['proved']}",
    f"- Source boundaries established: {summary['scope_boundary_established']}",
    f"- Obstruction hypotheses refuted: {summary['refuted']}",
    f"- Open obligations: {summary['open']}",
    f"- Active wave: {ledger['active_wave']}",'','## ADJ Status','',
    '- `GREL-001`: frozen neutral baseline; all comparison dimensions unresolved.',
    '- `W3.5-SDG-001`: frozen; not executed.',
    '- FARA-specificity: unresolved.',
    f"- RCS-001 admission framework: {'frozen' if scope['framework_frozen'] else 'not frozen'}.",
    f"- Concrete reasoning/contrast corpus: {scope['concrete_corpus_status']}.",
    '- Candidate ablation and reconstruction: not started.','','## USD Status','',
    '- `THM-US-TARGET-001`: frozen prospective.',
    f"- `US-CANDIDATES-001`: {len(candidates['candidates'])} initial hypotheses, all unresolved.",
    '- Universal structure: unresolved.',
    '- No-single-kernel alternative: unproved.','','## Comparative Representation Status','',
    'CRE-001: deterministic comparison complete at its registered retrospective scope under compiler-authored declared interpretations.',
    '',
    'CRE-002: prospective semantic-licensing result complete under Baseline 1.0; all three candidates remain unsupported because the five required capability classes were not licensed.',
    '',
    'CRE-002-EXT-001: prospective bounded execution complete under Baseline 1.1; all three candidates are complete for the registered scenario, ambiguity policies, derived machinery, and verifier conditions.',
    '',
    'These comparative results do not establish independent evidence, primitive-only sufficiency, universal structure, necessity, minimality, or superiority.','','## Current Evidence Conclusion','',
    'W0–W3 establish project-authored finite REP construction results for frozen `S_core`. They do not establish a representation theorem or universal structure. W4 and W3.5 are active in parallel. W5 is blocked until both resolve with linked evidence.','','## Relevant Reports','']
    lines += [f"- {markdown_link(ROOT/path,OUT,label)}" for label,path in REPORTS]
    lines += ['','## Navigation','',*nav()]
    OUT.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(OUT.relative_to(ROOT)); return 0
if __name__=='__main__': raise SystemExit(main())
