#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from report_link_utils import markdown_link

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/reports/project-status-generated.md"


def load(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def nav() -> list[str]:
    return [
        f"- README Command Center: {markdown_link(ROOT / 'README.md', OUT)}",
        f"- Current Project Status: {markdown_link(ROOT / 'docs/project-status.md', OUT)}",
        f"- Historical Bounded Status: {markdown_link(OUT, OUT)}",
        f"- Research Gaps: {markdown_link(ROOT / 'docs/reports/research-gap-report.md', OUT)}",
        f"- Next Actions: {markdown_link(ROOT / 'docs/planning/next-actions.md', OUT)}",
    ]


def main() -> int:
    candidate = load("theory/evaluation/w3-5-candidate-test-result-v1.0.json")
    gate = load("theory/evaluation/w3-5-specificity-and-discovery-gate.json")
    scope = load("theory/evaluation/reasoning-and-contrast-scope-v1.0.json")
    dimensions = load("theory/evaluation/w3-5-factorization-result-v1.0.json")["dimensions"]
    discrimination = load("theory/evaluation/w3-5-reasoning-discrimination-result-v1.0.json")["registered_results"]
    specificity = load("theory/evaluation/w3-5-fara-specificity-result-v1.0.json")["result"]
    structural = candidate["axis_counts"]["structural_commitment_necessity"]
    primitive = candidate["axis_counts"]["primitive_necessity"]
    explicit = candidate["axis_counts"]["explicit_representation_necessity"]
    reasoning = candidate["axis_counts"]["reasoning_specificity"]
    architecture = candidate["axis_counts"]["architecture_invariance"]

    lines = [
        "# Historical Bounded-Program Status (Generated)",
        "",
        "## Navigation",
        "",
        *nav(),
        "",
        "Generated by `python tools/project_status_report.py` from frozen W3.5-era evaluation artifacts.",
        "",
        "**Authority boundary:** this report is a historical/advisory projection and is not a current project-status authority. Use `docs/project-status.md` for current governance and milestone state. If any generated statement conflicts with a current canonical authority surface, the generated statement loses no ambiguity by recency and must not be used to break the tie.",
        "",
        "## Frozen W3.5 Snapshot",
        "",
        f"- W3.5 status recorded by the frozen gate: `{gate['status']}`.",
        "- Corpus, factorization, registered discrimination, qualified FARA-specificity, registered candidate execution, machinery/cost closure, claim-impact audit, and preserved-failure closure were complete at this snapshot.",
        "- Candidate execution preserves 648 of 648 required atomic trials.",
        "- At this historical point, W5 theorem assembly was authorized to begin.",
        "- W3.5 closure itself did not prove a theorem.",
        "",
        "## Registered ADJ Results at the Snapshot",
        "",
        f"- Corpus: {len(scope['positive_instances'])} positive, {len(scope['contrast_instances'])} contrast, {len(scope['disputed_instances'])} disputed.",
        f"- Factorization: `{dimensions['overall_interpretation']}`; expressiveness `{dimensions['expressiveness']}`; translation `{dimensions['translation']}`; cost `{dimensions['cost_relation']}`.",
        f"- Discrimination: {discrimination['positive']['reasoning_like']}/8 positives reasoning-like; {discrimination['contrast']['nonreasoning_like']}/8 contrasts nonreasoning-like; {discrimination['disputed']['borderline']}/2 disputed borderline.",
        f"- FARA specificity: `{specificity['classification']}`; unique capacity `{specificity['unique_discriminative_capacity_of_fara']}`.",
        f"- Candidate aggregate: `{candidate['aggregate_result']}`.",
        f"- Primitive necessity: supported {primitive['supported_at_registered_scope']}, refuted {primitive['refuted_at_registered_scope']}, partial {primitive['partial']}, unresolved {primitive['unresolved']}.",
        f"- Explicit-representation necessity: supported {explicit['supported_at_registered_scope']}, refuted {explicit['refuted_at_registered_scope']}, partial {explicit['partial']}, unresolved {explicit['unresolved']}.",
        f"- Structural-commitment necessity: supported {structural['supported_at_registered_scope']}, refuted {structural['refuted_at_registered_scope']}, partial {structural['partial']}, unresolved {structural['unresolved']}.",
        f"- Reasoning specificity: supported {reasoning['supported_at_registered_scope']}, refuted {reasoning['refuted_at_registered_scope']}, partial {reasoning['partial']}, unresolved {reasoning['unresolved']}.",
        f"- Architecture invariance: supported {architecture['supported_at_registered_scope']}, refuted {architecture['refuted_at_registered_scope']}, partial {architecture['partial']}, unresolved {architecture['unresolved']}.",
        "- Candidate evidence status: complete project-authored internal execution; not independent replication.",
        "- Cross-package cost result: tradeoff preserved; no superiority claim authorized.",
        "",
        "## Comparative Representation Snapshot",
        "",
        "CRE-001: deterministic comparison complete at its registered retrospective scope under compiler-authored declared interpretations.",
        "",
        "## Validation Investigation Snapshot",
        "",
        "- VI-002: `Research / incomplete (non-passing)`; 3 of 7 required methodology steps were complete at this snapshot.",
        "- Missing VI-002 evidence at this snapshot: per-removal architecture and FARA-consumer reconstructions, per-removal VI-001 executions, and a complete hidden-assumption ledger.",
        "- T-001 remained a distinct conditional five-primitive deletion-only theorem with no declared dependency on VI-002.",
        "",
        "## USD Snapshot",
        "",
        "- Universal structure was unresolved at this historical snapshot.",
        "- No universal nonexistence, universal necessity, minimality, or uniqueness conclusion was authorized by this snapshot alone.",
        "",
        "## Navigation",
        "",
        *nav(),
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
