#!/usr/bin/env python3
"""Validate and summarize the FAR adversarial evaluation registry.

This tool checks registry consistency only. It does not perform automated
reasoning and does not classify adversarial tests.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SUITE = ROOT / "theory" / "falsification" / "adversarial-test-suite.yaml"
DEFAULT_REPORT = ROOT / "docs" / "reports" / "adversarial-evaluation-report.md"

REQUIRED_FIELDS = [
    "id",
    "title",
    "reasoning_system",
    "hypothesis",
    "primitive_under_pressure",
    "expected_outcome",
    "observed_outcome",
    "current_status",
    "confidence",
    "notes",
]

PRIMITIVES = [
    "Investigation",
    "Representation",
    "Representational Structure",
    "Interpretation",
    "Reasoning Calculus",
]

PENDING_STATUS = "pending analysis"
PASSED_STATUSES = {"passed", "no primitive failure"}
FAILED_STATUSES = {"failed", "primitive failure"}
UNRESOLVED_STATUSES = {"pending analysis", "unresolved", "needs review"}


def load_yaml(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def validate_suite(data: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(data, dict):
        return ["suite root must be a mapping"]
    tests = data.get("tests")
    if not isinstance(tests, list):
        return ["suite must contain a tests list"]

    seen_ids: set[str] = set()
    for index, test in enumerate(tests, start=1):
        if not isinstance(test, dict):
            errors.append(f"test #{index} must be a mapping")
            continue
        for field in REQUIRED_FIELDS:
            if field not in test:
                errors.append(f"test #{index} missing required field: {field}")
        test_id = test.get("id")
        if isinstance(test_id, str):
            if test_id in seen_ids:
                errors.append(f"duplicate test id: {test_id}")
            seen_ids.add(test_id)
        primitive = test.get("primitive_under_pressure")
        if primitive not in PRIMITIVES:
            errors.append(f"test {test_id or index} has unknown primitive_under_pressure: {primitive}")
    return errors


def summarize(tests: list[dict[str, Any]]) -> dict[str, Any]:
    status_counts = Counter(test.get("current_status", "") for test in tests)
    pending = status_counts.get(PENDING_STATUS, 0)
    analyzed = sum(count for status, count in status_counts.items() if status != PENDING_STATUS)
    primitive_groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for test in tests:
        primitive_groups[test["primitive_under_pressure"]].append(test)

    primitive_rows = []
    for primitive in PRIMITIVES:
        grouped = primitive_groups.get(primitive, [])
        statuses = Counter(test.get("current_status", "") for test in grouped)
        passed = sum(statuses.get(status, 0) for status in PASSED_STATUSES)
        failed = sum(statuses.get(status, 0) for status in FAILED_STATUSES)
        unresolved = sum(statuses.get(status, 0) for status in UNRESOLVED_STATUSES)
        unresolved += len(grouped) - passed - failed - unresolved
        primitive_rows.append(
            {
                "primitive": primitive,
                "tests": len(grouped),
                "passed": passed,
                "failed": failed,
                "unresolved": unresolved,
            }
        )

    total_unresolved = sum(row["unresolved"] for row in primitive_rows)
    return {
        "total_adversarial_tests": len(tests),
        "pending": pending,
        "analyzed": analyzed,
        "unresolved": total_unresolved,
        "status_counts": dict(sorted(status_counts.items())),
        "primitive_pressure": primitive_rows,
        "tests_by_primitive": {primitive: len(items) for primitive, items in sorted(primitive_groups.items())},
    }


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Adversarial Evaluation Report",
        "",
        "Status: Automatically generated by `tools/run_adversarial_suite.py`.",
        "",
        "## Summary",
        "",
        f"- total adversarial tests: {summary['total_adversarial_tests']}",
        f"- pending: {summary['pending']}",
        f"- analyzed: {summary['analyzed']}",
        f"- unresolved: {summary['unresolved']}",
        "",
        "## Primitive Pressure Table",
        "",
        "| Primitive | Tests | Passed | Failed | Unresolved |",
        "|---|---:|---:|---:|---:|",
    ]
    for row in summary["primitive_pressure"]:
        lines.append(
            f"| {row['primitive']} | {row['tests']} | {row['passed']} | {row['failed']} | {row['unresolved']} |"
        )
    lines.extend(
        [
            "",
            "## Current Status",
            "",
            "No adversarial conclusions have yet been reached.",
            "",
            "The purpose of the suite is to organize future falsification efforts.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate and summarize the FAR adversarial suite")
    parser.add_argument("--suite", type=Path, default=DEFAULT_SUITE)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--json", action="store_true", help="emit JSON summary")
    parser.add_argument("--write-report", action="store_true", help="write Markdown report")
    args = parser.parse_args()

    data = load_yaml(args.suite)
    errors = validate_suite(data)
    if errors:
        for error in errors:
            print(f"error: {error}")
        return 1

    tests = data["tests"]
    summary = summarize(tests)
    markdown = render_markdown(summary)

    if args.write_report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(markdown, encoding="utf-8")

    if args.json:
        print(json.dumps(summary, indent=2, sort_keys=True))
    else:
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
